version: "3.7"
services:
  app:
    build: .
    image: owntools/express-api
    command: yarn start
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      # ignore generated files
      - /usr/src/app/node_modules
    # for debugger
    stdin_open: true
    tty: true

  test:
    image: owntools/express-api
    command: /wait-for-it.sh app:8080 -- yarn test
    depends_on:
      - app
    environment:
      API_URL: http://app:8080
    volumes:
      - ".:/usr/src/app"
      # ignore generated files
      - /usr/src/app/node_modules
