version: "3.7"
services:
  app:
    build:
      context: .
      cache_from:
        - owntools/express-api
    image: owntools/express-api
    command: yarn start
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true
