version: "3.7"
services:
  server:
    build: server
    command: yarn start
    ports:
      - "8081:8081"
    volumes:
      - "./server:/usr/src/app"
      # ignore generated files
      - /usr/src/app/node_modules

  app:
    build: .
    image: owntools/react-webapp
    command: yarn start
    depends_on:
      - server
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      # ignore generated files
      - /usr/src/app/.cache
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    # for debugger
    stdin_open: true
    tty: true

  test:
    # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ipc: host
    # 3.7.0 seems to be a known good version https://github.com/cypress-io/cypress/issues/349#issuecomment-570179689
    image: cypress/included:3.7.0
    # wait for server, then wait for react app to listen on host/port
    command: /wait-for-it.sh server:8081 -- /wait-for-it.sh app:8080 -- cypress run
    depends_on:
      - app
    volumes:
      - "./.owntools:/e2e"
    working_dir: "/e2e"
