version: "3.7"
services:
  server:
    build: server
    command: yarn start
    ports:
      - "8081:8081"
    volumes:
      - "./server:/usr/src/app"
      # ignore generated files
      - /usr/src/app/node_modules

  app:
    build: .
    image: owntools/react-webapp
    command: yarn start
    depends_on:
      - server
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      # ignore generated files
      - /usr/src/app/.cache
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    # for debugger
    stdin_open: true
    tty: true

  test:
    # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ipc: host
    # 3.7.0 seems to be a known good version https://github.com/cypress-io/cypress/issues/349#issuecomment-570179689
    image: cypress/included:3.7.0
    # container run options
    # entrypoint: bash
    # command: --browser chrome
    depends_on:
      - app
    environment:
      CYPRESS_baseUrl: http://app:8080
      CYPRESS_serverUrl: http://server:8081
    volumes:
      - "./__owntools__:/e2e"
    working_dir: "/e2e"
