version: "3.7"
services:
  app:
    build:
      context: .
      cache_from:
       - owntools/python2
    image: owntools/python2
    command: python app.py
    environment:
      PYTHONPATH: .
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true
