version: "3.7"
services:
  app:
    build: .
    image: owntools/python3
    command: python app.py
    environment:
      PYTHONPATH: .
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true
