[tool.poetry]
name = "flask-api"
version = "0.0.1"
description = ""
authors = ["smoll"]

[tool.poetry.dependencies]
python = "3.7.5"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
