version: "3.7"
services:
  app:
    build: .
    image: owntools/flask-api
    command: python app.py
    environment:
      PYTHONPATH: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true

  test:
    image: owntools/flask-api
    command: python test.py
    depends_on:
      - app
    environment:
      API_HOST: 'app'
      API_PORT: '5000'
      PYTHONPATH: .
    volumes:
      - ".:/usr/src/app"
