version: "3.7"
services:
  app:
    build: .
    image: owntools/flask-api
    command: python app.py
    environment:
      PORT: "8080"
      PYTHONPATH: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true

  test:
    image: owntools/flask-api
    command: /wait-for-it.sh app:8080 -- python test.py
    depends_on:
      - app
    environment:
      API_URL: http://app:8080
      PYTHONPATH: .
    volumes:
      - ".:/usr/src/app"
