version: "3.7"
services:
  app:
    build:
      context: .
      cache_from:
        - owntools/flask-api
    image: owntools/flask-api
    command: python app.py
    environment:
      PORT: "8080"
      PYTHONPATH: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true
