version: "3.7"
services:
  app:
    build:
      context: .
      cache_from:
       - owntools/nodejs
    image: owntools/nodejs
    command: yarn start
    volumes:
      - ".:/usr/src/app"
    # for debugger
    stdin_open: true
    tty: true
