version: "3.7"
services:
  app:
    build: .
    image: owntools/nodejs
    command: yarn start
    volumes:
      - ".:/usr/src/app"
      # ignore generated files
      - /usr/src/app/node_modules
    # for debugger
    stdin_open: true
    tty: true
