name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-buildx1-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx1-

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Run Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker buildx build \
            --cache-to=type=local,dest=docker-cache \
            --output "type=image,push=false" \
            --tag owntools/react-app \
            --file ./react-app/Dockerfile ./react-app

          docker buildx build \
            --cache-to=type=local,dest=docker-cache \
            --output "type=image,push=false" \
            --tag owntools/json-server \
            --file ./react-app/server/Dockerfile ./react-app/server

      - name: Check docker images
        run: docker images

      - name: Test all
        run: cd react-app && make test # make test
