name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check docker daemon
      run: docker ps
    - name: Test all
      run: make test
    - name: Check docker images
      run: docker images
