name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Docker daemon
        run: docker ps

      - uses: actions/cache@v1
        id: cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Load cached Docker layers
        run: |
          if [ -d "docker-cache" ]; then
            make load
            rm -rf docker-cache
          fi

      - name: Build images
        if: steps.cache.outputs.cache-hit != 'true'
        run: make caching-build

      - name: Test all
        run: make test

      - name: Check Docker images
        run: docker images
